config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :recipes do
    resources :ingredients, only: [:create, :destroy]
    resources :prep_steps, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    member do
      put "hmm", to: "recipes#hmm"
    end
  end

  get 'myrecipes' => 'recipes#myrecipes'
  root 'recipes#index'

end

app/models/hmm.rb
class Hmm < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :user_id, scope: :recipe_id
  validates :user_id, presence: true
  validates :recipe_id, presence: true
  validate :cannot_hmm_own_recipe

  def cannot_hmm_own_recipe
    if self.recipe.present? and self.recipe.user == self.user
      self.recipe.errors.add(:base, I18n.t(:hmm_own_recipe_not_permitted))
      errors.add(:base, I18n.t(:hmm_own_recipe_not_permitted))
    end
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
  validates :ingredient, presence: true
end

app/models/prep_step.rb
class PrepStep < ActiveRecord::Base
  belongs_to :recipe
  validates :description, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, dependent: :destroy
  has_many :prep_steps, dependent: :destroy
  has_many :hmms, dependent: :destroy
  has_many :users, -> { uniq }, through: :hmms
  has_many :reviews
  belongs_to :user
  validates :name, presence: true, length: { maximum: 50 }
  validates :cooking_time, presence: :true
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "400x400" }
  validates_attachment :image, presence: true,
    content_type: { content_type: "image/jpeg" }

  def hmm_by (user)
    @hmm = self.hmms.new
    @hmm.user = user
    return @hmm.save
  end

  def belongs_to? (user)
    self.user == user
  end

  def self.search (query)
    where("name like ?", "%#{query}%")
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes, through: :hmms
  has_many :hmms
  has_many :recipes
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!

  def ingredient
    ingredient ||= Ingredient.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.build(ingredient_params)
    unless @ingredient.save
      flash[:error] = t(:fill_ingredient)
    end
    redirect_to recipe_path(@recipe)
  end

  def destroy
    if ingredient.destroy
      flash[:success] = t(:deleted_ingredient)
    end
    redirect_to request.referrer || root_url
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:ingredient)
  end
end

app/controllers/prep_steps_controller.rb
class PrepStepsController < ApplicationController
  before_action :authenticate_user!

  def prep_step
    prep_step ||= PrepStep.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @prep_step = @recipe.prep_steps.build(prep_step_params)
    unless @prep_step.save
      flash[:error] = t(:fill_prep_step)
    end
    redirect_to recipe_path(@recipe)
  end

  def destroy
    if prep_step.destroy
      flash[:success] = t(:deleted_prep_step)
    end
    redirect_to request.referrer || root_url
  end

  private
  def prep_step_params
   params.require(:prep_step).permit(:description)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search]
      @recipes = Recipe.search(params[:search])
    else
      @recipes = Recipe.all
    end

    flash[:info] = t(:no_recipes_to_show) if @recipes.empty?
  end

  def show
    @ingredient = Ingredient.new
    @prep_step = PrepStep.new
    @review = Review.new
    recipe
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      flash[:success] = t(:recipe_saved)
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def update; end

  def myrecipes
    @recipes = Recipe.where(user: current_user)

    flash[:info] = t(:no_recipes_created) if @recipes.empty?
  end

  def hmm
    unless recipe.hmm_by(current_user)
      flash[:danger] = recipe.errors.full_messages.last
    end

    redirect_to request.referrer || root_url
  end

  def destroy
    recipe.destroy
    redirect_to request.referrer || root_url
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cooking_time, :image, :search)
  end

  def recipe
    @recipe ||= Recipe.find(params[:id])
  end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.build(review_params)
    @review.user = current_user
    unless @review.save
      flash[:error] = t(:fill_review)
    end
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:success] = t(:deleted_review)
    end
    redirect_to request.referrer || root_url
  end

  private
  def ingredient_params
    params.require(:review).permit(:review, :stars)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.build(review_params)
    @review.user = current_user
    unless @review.save
      flash[:error] = t(:fill_review)
    end
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:success] = t(:deleted_review)
    end
    redirect_to request.referrer || root_url
  end

  private
  def review_params
    params.require(:review).permit(:review, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/ingredients/_ingredient.html.erb
<li class="list-group-item">
  <%= ingredient.ingredient %>
  <!-- See how to make this code better -->
  <% if(ingredient.recipe.belongs_to?(current_user)) %>
    <%= link_to "x", { :action=>"destroy", :controller=>"ingredients",
                        :id => ingredient.id, :recipe_id => ingredient.recipe.id },
                       method: :delete, data: { confirm: t(:sure_delete) } %>
  <% end %>
</li>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Foram encontrados <%= pluralize(object.errors.count, "erro") %> no formulário.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    HmmDelicious por Guilherme Figueiroa
  </small>
  <nav>

  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "HmmDelicious", root_path, id: "logo" %>
    <nav>
      <%= form_tag recipes_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Pesquisar receitas", class: "form-control" %>
          <!--%= submit_tag "Pesquisar", :name => nil, class: "btn btn-default" %-->
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(:home), root_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to t(:new_recipe), new_recipe_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(:options) %> <b class="caret"></b>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to(t(:my_recipes), myrecipes_path ) %>
                </li>
                <li>
                  <%= link_to(t(:logout), destroy_user_session_path, :method => :delete) %>
                </li>
              </ul>
            </a>
          </li>
        <% else %>
          <li><%= link_to "Entrar", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HmmDelicious</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  </br>
  <!--%= debug(params) if Rails.env.development? %-->
</div>
</body>
</html>

app/views/prep_steps/_prep_step.html.erb
<li class="list-group-item">
  <%= prep_step.description %>
  <% if(prep_step.recipe.belongs_to?(current_user)) %>
    <%= link_to "x", { :action=>"destroy", :controller=>"prep_steps",
                        :id => prep_step.id, :recipe_id => prep_step.recipe.id },
                       method: :delete, data: { confirm: t(:sure_delete) } %>
  <% end %>
</li>

app/views/recipes/_list_item.html.erb
<li class="list-group-item">

  <% if(list_item.recipe.belongs_to?(current_user)) %>
    <%= link_to "x", { action: "destroy", controller: controller_name,
                        id: list_item.id, recipe_id: list_item.recipe.id },
                       method: :delete, data: { confirm: t(:sure_delete) } %>
  <% end %>
</li>

app/views/recipes/_recipe.html.erb
<div class="col-md-3 col-sm-6 col-xs-12 ">

  <div class="recipe_info">
    <div id="recipe_image">
      <%= link_to image_tag(recipe.image.url(:large)), recipe %>
      <% if recipe.belongs_to?(current_user) %>
        <%= button_to t(:delete), recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
      <% end %>
    </div>
    <p><%= link_to recipe.name, recipe %></p>
    <p><%= recipe.cooking_time %><%= " "+t(:minutes) %></p>
    <% if user_signed_in? %>
      <p>
        <%= link_to "Hmm"+" ("+recipe.hmms.size.to_s+")", hmm_recipe_path(recipe), method: :put %>
      </p>
    <% end %>
  </div>
</div>

app/views/recipes/_recipe_list.html.erb
<%= @recipes.each_slice(4) do |recipes| %>
  <div class="row">
    <%= render recipes %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<%= @recipes.each_slice(3) do |recipes| %>
  <div class="row">
    <%= render recipes %>
  </div>
<% end %>

app/views/recipes/myrecipes.html.erb
<%= render 'recipe_list', object: @recipes %>

app/views/recipes/new.html.erb
<div class="row">
  <%= form_for @recipe, html: { multipart: true, class: "col-md-8" } do |f| %>
    <%= render 'layouts/error_messages', object: f.object %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </p>

    <p>
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </p>

    <p>
      <%= f.label :cooking_time %>
      <%= number_field(:recipe, :cooking_time, in: 1..120, step: 1) %>
    </p>

    <p>
      <%= f.file_field :image %>
    </p>

    <%= f.submit "Criar receita", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col-md-12">
    <section class="recipe_info">
      <h1>
        <%= @recipe.name %>
        <% unless @recipe.user == current_user %>
          <%= link_to("#{t(:hmm)}(#{@recipe.hmms.size.to_s})", hmm_recipe_path(@recipe), method: :put) %>
        <% end %>
      </h1>
      <h2>
        <%= @recipe.description %>
      </h2>

      <div class="recipe_image">
        <%= image_tag(@recipe.image.url(:large)) %>
      </div>

    </section>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Ingredientes</h4></div>
      <ul class="list-group">
        <%= render @recipe.ingredients %>
      </ul>

      <% if @recipe.belongs_to?(current_user) %>
        <div class="panel-footer">
          <%= form_for @ingredient, url: recipe_ingredients_path(@recipe), html: { class: "form-inline" } do |f| %>
            <div class="form-group">
              <%= f.text_field :ingredient, placeholder: (t :placeholder_new_ingredient), class: "form-control" %>
            </div>
            <%= f.submit t(:add), class: "btn btn-default" %>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>

  <div class="col-md-6">
   <div class="panel panel-default">
      <div class="panel-heading"><h4>Modo de preparo</h4></div>
      <ul class="list-group">
        <%= render @recipe.prep_steps %>
      </ul>


      <% if @recipe.belongs_to?(current_user) %>
        <div class="panel-footer">
          <%= form_for @prep_step, url: recipe_prep_steps_path(@recipe), html: { class: "form-inline" } do |f| %>
            <div class="form-group">
              <%= f.text_area :description, placeholder: (t :placeholder_new_step), class: "form-control"  %>
            </div>
            <%= f.submit t(:add), class: "btn btn-default" %>
          <% end %>
        </div>
      <% end %>

    </article>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Comentários</h4></div>

      <%= render @recipe.reviews %>
      <%= form_for @review, url: recipe_reviews_path(@recipe), html: { class: "form-inline" } do |f| %>
          <div class="form-group">
            <%= f.text_area :review, placeholder: (t :placeholder_new_review), class: "form-control"  %>
          </div>
          <%= f.submit t(:add), class: "btn btn-default" %>
        <% end %>
    </div>
  </div>
</div>

app/views/reviews/_review.html.erb
<li class="list-group-item">
  <b><%= "#{review.user.name}: " %></b>
  <%= review.review %>
  <%= review.stars %>
</li>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
<%= link_to t(:sign_in), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to t(:sign_up), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
<%= link_to t(:forgot_your_password), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<%= link_to t('.didn_t_receive_confirmation_instructions', :default => "Didn't receive confirmation instructions?"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<%= link_to t('.didn_t_receive_unlock_instructions', :default => "Didn't receive unlock instructions?"), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
  <%= link_to t('.sign_in_with_provider', :provider => provider.to_s.titleize, :default => "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(:sign_in), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(:sign_up), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(:forgot_your_password), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>